"""Discover Verily Workbench resources and write a sourceable .workspace_env.

VERIFY/ADAPT IN YOUR WORKSPACE: the `wb resource list` shapes (bucket ids, how
the CDR is surfaced) vary between workspaces. This covers the common case; if
your CDR is an external read-only project not in `wb resource list`, pass it
explicitly with --cdr. Validate the discovered values before relying on them.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

_VAR_ORDER = (
    "GOOGLE_CLOUD_PROJECT",
    "WORKSPACE_CDR",
    "WORKSPACE_BUCKET",
    "WORKSPACE_TEMP_BUCKET",
)


def _wb(*args: str):
    """Run `wb <args> --format=json` and parse stdout as JSON."""
    cmd = ["wb", *args, "--format=json"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except FileNotFoundError:
        print("ERROR: 'wb' CLI not found. Are you on a Verily Workbench cluster?",
              file=sys.stderr)
        sys.exit(2)
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: `{' '.join(cmd)}` failed (exit {exc.returncode})", file=sys.stderr)
        if exc.stderr:
            print(exc.stderr, file=sys.stderr)
        sys.exit(2)
    return json.loads(proc.stdout)


def discover(wb=_wb) -> dict[str, str]:
    """Pull workspace-shape values from the wb CLI (injectable for testing)."""
    out: dict[str, str] = {}
    workspace = wb("workspace", "describe")
    out["GOOGLE_CLOUD_PROJECT"] = workspace["googleProjectId"]
    for r in wb("resource", "list"):
        rt = r.get("resourceType", "")
        if rt == "GCS_BUCKET":
            rid, bucket = r.get("id", ""), r.get("bucketName")
            if not bucket:
                continue
            # Order matters: the temp bucket id also contains "workspace-bucket".
            if "temporary-workspace-bucket" in rid:
                out["WORKSPACE_TEMP_BUCKET"] = f"gs://{bucket}"
            elif "workspace-bucket" in rid:
                out["WORKSPACE_BUCKET"] = f"gs://{bucket}"
        elif rt in ("BQ_DATASET", "BIGQUERY_DATASET"):
            if "WORKSPACE_CDR" not in out:
                out["WORKSPACE_CDR"] = f"{r['projectId']}.{r['datasetId']}"
    return out


def render_env(values: dict[str, str]) -> str:
    """Render discovered values as sourceable `export` lines."""
    lines = [
        "# Generated by setup_workspace.py — do not edit by hand.\n",
        "# Regenerate via: make setup-workspace  (optionally CDR=<project>.<dataset>)\n",
    ]
    for k in _VAR_ORDER:
        if values.get(k):
            lines.append(f"export {k}='{values[k]}'\n")
    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cdr", default=None,
                        help="override WORKSPACE_CDR as <project>.<dataset>")
    parser.add_argument("--out", default=".workspace_env", help="output file path")
    args = parser.parse_args(argv)

    values = discover()
    if args.cdr:
        values["WORKSPACE_CDR"] = args.cdr
    if not values.get("WORKSPACE_CDR"):
        print("ERROR: WORKSPACE_CDR not found. Pass it: make setup-workspace "
              "CDR='<project>.<dataset>'", file=sys.stderr)
        return 1

    Path(args.out).write_text(render_env(values))
    summary = ", ".join(f"{k}={values[k]}" for k in _VAR_ORDER if values.get(k))
    print(f"Wrote {args.out}: {summary}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
